### ISSUE TITLE
PreventDefault for devtool button events

### ISSUE THREAD

**Issue by dsifford** [mobxjs/mobx-react-devtools#29]
Hi there.

Thanks for your work on this. Super useful.

One issue I'm running into is that, where I'm using the devtool, clicking any button causes the page to reload. Is `preventDefault` set on the click event for those buttons? If not, could it be?

**Comment by andykog** [comment]
@dsifford, that happens when you click devtool panel button, or picking observable component in «inspect dependencies» mode?
1. is totally unbelievable, as those buttons are quite ordinary react components with onClick props https://github.com/mobxjs/mobx-react-devtools/blob/master/src/Panel/PanelButton.jsx#L49
2. shouldn't happen because capturing is being used https://github.com/mobxjs/mobx-react-devtools/blob/df0cd13ed2c708137d552f7d32d52febec045cb9/src/Controls/GraphControl.jsx#L19 and the handler stops propagation if clicked on observable component https://github.com/mobxjs/mobx-react-devtools/blob/1594b6181dfc6ef244890564547eef88e9a264c0/src/globalStore.js#L98

Could you provide more details on how to reproduce the issue?

**Comment by dsifford** [comment]
Haha, it's number 1! 

The disbelief is completely understandable. I'm not even sure it's an issue with mobx-react-devtools proper. 

I'm using the devtools for a react project that I'm working on inside a wordpress plugin and wordpress freaks out and reloads the post editor whenever I click one of the buttons.

I've gotten around this by just adding a global click event listener that runs `preventDefault` for the time that I need to use the devtools, so I suppose this isn't totally a major concern. If this is just some weird edge case, then you can probably just call it fine as-is and I'll keep dealing with it how I've been.

Having said all that, there's also a large possibility that this is simply user-error.

Code lives here: 

https://github.com/dsifford/academic-bloggers-toolkit

**Edit:** The relevant code specifically lives here: https://github.com/dsifford/academic-bloggers-toolkit/blob/master/src/lib/js/reference-list/components/ReferenceList.tsx

**Comment by andykog** [comment]
@dsifford Hmm, I can imagine wordpress reloads after click on any button, just to make people suffer. Could you try placing `<button>test</button>` just after `<DevTool />` component? Does it also leads to page reload? By the way, is it possible, that your DevTool panel is somehow placed inside `<form></form>` html element?

**Comment by andykog** [comment]
If the answer to the last question is yes, this commit should fix this https://github.com/mobxjs/mobx-react-devtools/commit/b673df5b53a225812919d2625c105add6b0b26f4 (mistyped issue number)

**Comment by dsifford** [comment]
Yep, without even looking, that must be the case. The component is rendered within a metabox, which itself is completely wrapped in a form element.

Nice catch! I hadn't even thought of that. Thanks for the help 😄

**Comment by dsifford** [comment]
Let me test part 1 of your question here real quick... Give me just a sec.

**Comment by andykog** [comment]
@dsifford, no need, it will reload page without `type="button"` :-)

**Comment by dsifford** [comment]
@andykog Ok cool, thanks for the quick fix!

![not worthy](http://i.giphy.com/iiS84hOJXh1Pq.gif)

**Comment by mweststrate** [comment]
@andykog this fix is not released yet if I am correctly? feel free to do so :)

**Comment by andykog** [comment]
Published as `v4.2.5`
